# 速習torch

In [12]:
from __future__ import print_function
import torch

In [21]:
#　ランダムに初期化された行列を作成
x = torch.rand(5, 3)
print(x)
print(x.size())

#　スライスなどnumpy likeに扱える
print(x[:, 1])

tensor([[0.9950, 0.8168, 0.6981],
        [0.0420, 0.3956, 0.9324],
        [0.7310, 0.0864, 0.5840],
        [0.2433, 0.3650, 0.2506],
        [0.3126, 0.7840, 0.1970]])
torch.Size([5, 3])
tensor([0.8168, 0.3956, 0.0864, 0.3650, 0.7840])


In [23]:
#　加算
y = torch.ones(5, 3)
print(x + y)
print(torch.add(x, y))

#　out因数で出力tensorを用意
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.9950, 1.8168, 1.6981],
        [1.0420, 1.3956, 1.9324],
        [1.7310, 1.0864, 1.5840],
        [1.2433, 1.3650, 1.2506],
        [1.3126, 1.7840, 1.1970]])
tensor([[1.9950, 1.8168, 1.6981],
        [1.0420, 1.3956, 1.9324],
        [1.7310, 1.0864, 1.5840],
        [1.2433, 1.3650, 1.2506],
        [1.3126, 1.7840, 1.1970]])
tensor([[1.9950, 1.8168, 1.6981],
        [1.0420, 1.3956, 1.9324],
        [1.7310, 1.0864, 1.5840],
        [1.2433, 1.3650, 1.2506],
        [1.3126, 1.7840, 1.1970]])


In [30]:
# viewで並び替え
x_sort1 = x.view(15)
x_sort2 = x.view(-1, 5)
print(x.size(), x_sort1.size(), x_sort2.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [38]:
#　tensorをnumpyに変換
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)

#　tensorにした操作は変換先にも反映される
a.add_(1)
print(a)
print(b)

#　numpyからtensorに変換
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [36]:
#　toメソッドを使用して、テンソルを任意のデバイスに移動できます。
if torch.cuda.is_available():
    device = torch.device("cuda")          
    x = x.to(device)
    y = torch.ones_like(x, device=device)                      
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 

tensor([[1.9950, 1.8168, 1.6981],
        [1.0420, 1.3956, 1.9324],
        [1.7310, 1.0864, 1.5840],
        [1.2433, 1.3650, 1.2506],
        [1.3126, 1.7840, 1.1970]], device='cuda:0')
tensor([[1.9950, 1.8168, 1.6981],
        [1.0420, 1.3956, 1.9324],
        [1.7310, 1.0864, 1.5840],
        [1.2433, 1.3650, 1.2506],
        [1.3126, 1.7840, 1.1970]], dtype=torch.float64)
