# 速習torch

In [1]:
from __future__ import print_function
import torch

In [2]:
#　ランダムに初期化された行列を作成
x = torch.rand(5, 3)
print(x)
print(x.size())

#　スライスなどnumpy likeに扱える
print(x[:, 1])

tensor([[0.1917, 0.3405, 0.5191],
        [0.0555, 0.2899, 0.9191],
        [0.0844, 0.2913, 0.7757],
        [0.1771, 0.7732, 0.9604],
        [0.4159, 0.4367, 0.6654]])
torch.Size([5, 3])
tensor([0.3405, 0.2899, 0.2913, 0.7732, 0.4367])


In [3]:
#　加算
y = torch.ones(5, 3)
print(x + y)
print(torch.add(x, y))

#　out因数で出力tensorを用意
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.1917, 1.3405, 1.5191],
        [1.0555, 1.2899, 1.9191],
        [1.0844, 1.2913, 1.7757],
        [1.1771, 1.7732, 1.9604],
        [1.4159, 1.4367, 1.6654]])
tensor([[1.1917, 1.3405, 1.5191],
        [1.0555, 1.2899, 1.9191],
        [1.0844, 1.2913, 1.7757],
        [1.1771, 1.7732, 1.9604],
        [1.4159, 1.4367, 1.6654]])
tensor([[1.1917, 1.3405, 1.5191],
        [1.0555, 1.2899, 1.9191],
        [1.0844, 1.2913, 1.7757],
        [1.1771, 1.7732, 1.9604],
        [1.4159, 1.4367, 1.6654]])


In [4]:
# viewで並び替え
x_sort1 = x.view(15)
x_sort2 = x.view(-1, 5)
print(x.size(), x_sort1.size(), x_sort2.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [5]:
#　tensorをnumpyに変換
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)

#　tensorにした操作は変換先にも反映される
a.add_(1)
print(a)
print(b)

#　numpyからtensorに変換
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [6]:
#　toメソッドを使用して、テンソルを任意のデバイスに移動できます。
if torch.cuda.is_available():
    device = torch.device("cuda")          
    x = x.to(device)
    y = torch.ones_like(x, device=device)                      
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 

tensor([[1.1917, 1.3405, 1.5191],
        [1.0555, 1.2899, 1.9191],
        [1.0844, 1.2913, 1.7757],
        [1.1771, 1.7732, 1.9604],
        [1.4159, 1.4367, 1.6654]], device='cuda:0')
tensor([[1.1917, 1.3405, 1.5191],
        [1.0555, 1.2899, 1.9191],
        [1.0844, 1.2913, 1.7757],
        [1.1771, 1.7732, 1.9604],
        [1.4159, 1.4367, 1.6654]], dtype=torch.float64)
